language: node_js
node_js:
  - "node"
  - "iojs"
  - "7"
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@6.2.0
install:
  - npm install
script:
  - npm test